# Chapter 3 - Exercise 4: Weather Data

#### Bộ dữ liệu Weather Data bao gồm thông tin về thời tiết của tất cả các ngày trong tháng 7 năm 2017
#### Bộ dữ liệu chứa trong thư mục data gồm các file dữ liệu:
- 1_TempHighF: Nhiệt độ cao nhất (độ F)
- 2_TempLowF: Nhiệt độ thấp nhất (độ F)
- 3_HumidityHighPercent: Độ ẩm cao nhất (%)
- 4_HumidityLowPercent: Độ ẩm thấp nhất (%)
- 5_VisibilityHighMiles: Tầm nhìn xa (miles)
- 6_VisibilityLowMiles: Tầm nhìn gần (miles)
- 7_WindMPH: Sức gió (miles per hour)
- 8_PrecipitationSumInches: Lượng mưa (inches)

### * Yêu cầu
<p><b>1. Đọc dữ liệu từ các tập tin trong thư mục "Weather Data" và tạo dataframe dfWeather với tên cột tương ứng (ví dụ tên file "1_TempHighF.txt" thì tên cột là "TempHighF")  
</b></p>
- Xem 5 dòng đầu tiên trong dfWeather  <br>
- Kiểm tra và chuyển đổi kiểu dữ liệu phù hợp

<p><b>2. Tạo dataframe dfWeather2 lần lượt với các cột sau đây:
'TempHighC', 'TempLowC', 'HumidityHighPercent', 'HumidityLowPercent', 'VisibilityHighKMs', 'VisibilityLowKMs', 'WindKMPH', 'PrecipitationSumMM'</b></p>  
<p>&nbsp; &nbsp;2.1  Chuyển đổi cột nhiệt độ cao nhất từ độ F sang độ C và lưu vào cột TempHighC trong dfWeather2 (làm tròn 2 số lẻ), hiển thị 5 giá trị đầu của TempHighC</p>
<ul>
    <li>công thức chuyển từ độ F sang C: C = (F − 32) × 5/9</li>
    <li>ví dụ chuyển từ 80F sang C: C = (80 - 32) x 5/9 = 26.67C</li>
</ul>    
<p>&nbsp; &nbsp;2.2 Chuyển đổi cột nhiệt độ thấp nhất từ độ F sang độ C và lưu vào cột TempLowC trong dfWeather2</p>
<p>&nbsp; &nbsp;2.3 Tính nhiệt độ trung bình TempMediumC trong dfWeather2</p>
<p>&nbsp; &nbsp;2.4 Tạo mới các cột độ ẩm HumidityHighPercent và HumidityLowPercent trong dfWeather2 bằng các cột HumidityHighPercent và HumidityLowPercent trong dfWeather</p>
<p>&nbsp; &nbsp;2.5 Chuyển đổi cột tầm nhìn xa từ miles sang kilomet và lưu vào cột VisibilityHighKMs trong dfWeather2</p>
<ul>
<li>công thức chuyển từ Mile sang Kilomet: km = mile * 1.609344</li>
    <li>ví dụ chuyển từ 10 mile sang km: km = 10 * 1.609344 = 16.09344 km</li>
</ul>    
<p>&nbsp; &nbsp;2.6 Chuyển đổi cột tầm nhìn gần từ miles sang kilomet và lưu vào cột VisibilityLowKMs trong dfWeather2</p>
<p>&nbsp; &nbsp;2.7 Chuyển đổi cột sức gió từ miles/hour (WindMPH) sang kilomets/hour và lưu vào cột WindKMPH trong dfWeather2</p>
<p>&nbsp; &nbsp;2.8 Chuyển đổi cột lượng mưa từ inches sang milimet và lưu vào cột PrecipitationSumMMs trong dfWeather2</p>
<ul>
    <li>công thức chuyển từ Inches sang Milimet: mm = inches * 25.4</li>
    <li>ví dụ chuyển từ 10 inches sang milimet: mm = 10 * 25.4 = 254 mm</li>

<p><b>3. Xem thông tin thời tiết của 5 ngày đầu tiên trong dfWeather2
<p><b>4. Từ dfWeather2, liệt kê thông tin thời tiết của các ngày có nhiệt độ trung bình cao nhất
<p><b>5. Từ dfWeather2, liệt kê thông tin thời tiết của các ngày có nhiệt độ trung bình thấp nhất
<p><b>6. Từ dfWeather2, liệt kê thông tin thời tiết của các ngày có mưa, sắp giảm theo lượng mưa
<p><b>7. Từ dfWeather2, liệt kê thông tin thời tiết của các ngày không có mưa và có độ ẩm trung bình cao nhất
<p><b>8. Tạo series temp_medium chứa hai giá trị trung bình cột TempMediumC của các ngày có mưa và các ngày không mưa trong tháng

In [1]:
import os
import pandas as pd
import re

#### 1. Đọc dữ liệu từ các tập tin và tạo dataframe dfWeather với tên cột tương ứng

In [2]:
# Lấy danh sách tên các tệp trong thư mục
file_list = os.listdir('Weather Data')
file_list

['1_TempHighF.txt',
 '2_TempLowF.txt',
 '3_HumidityHighPercent.txt',
 '4_HumidityLowPercent.txt',
 '5_VisibilityHighMiles.txt',
 '6_VisibilityLowMiles.txt',
 '7_WindMPH.txt',
 '8_PrecipitationSumInches.txt']

In [3]:
dfWeather = pd.DataFrame()
# Đọc từng tệp và tạo DataFrame từ nội dung của từng tệp
for file_name in file_list:
    # if file_name.endswith('.txt'): nếu thư mục chứa nhiều loại file
    file_path = 'Weather Data/' + file_name
    with open(file_path, 'r', encoding='utf-8') as file:
        content = file.read()
        #column_name = file_name.split('.')[0].split('_')[1]  # Tên cột chính là tên của tệp
        column_name = re.search('([A-Za-z]+)', file_name).group(1) # dùng regular expression
        dfWeather[column_name] = content.split(',')

# Hiển thị 5 dòng đầu của DataFrame
dfWeather.head()

,TempHighF,TempLowF,HumidityHighPercent,HumidityLowPercent,VisibilityHighMiles,VisibilityLowMiles,WindMPH,PrecipitationSumInches
0,98,79,85,38,10,6,15,0.01
1,100,78,91,35,10,8,14,0
2,99,76,88,35,10,10,13,0
3,101,78,85,35,10,10,13,0
4,99,78,85,31,10,10,13,0

In [4]:
dfWeather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   TempHighF               31 non-null     object
 1   TempLowF                31 non-null     object
 2   HumidityHighPercent     31 non-null     object
 3   HumidityLowPercent      31 non-null     object
 4   VisibilityHighMiles     31 non-null     object
 5   VisibilityLowMiles      31 non-null     object
 6   WindMPH                 31 non-null     object
 7   PrecipitationSumInches  31 non-null     object
dtypes: object(8)
memory usage: 2.1+ KB

In [5]:
# Chuyển kiểu dữ liệu của tất cả các cột trong dfWeather thành numeric
dfWeather = dfWeather.apply(pd.to_numeric)
dfWeather.head()

,TempHighF,TempLowF,HumidityHighPercent,HumidityLowPercent,VisibilityHighMiles,VisibilityLowMiles,WindMPH,PrecipitationSumInches
0,98,79,85,38,10,6,15,0.01
1,100,78,91,35,10,8,14,0.00
2,99,76,88,35,10,10,13,0.00
3,101,78,85,35,10,10,13,0.00
4,99,78,85,31,10,10,13,0.00

### 2. Tạo dataframe dfWeather2 lần lượt với các cột sau đây:
- 'TempHighC', 'TempLowC', 'HumidityHighPercent', 'HumidityLowPercent', 'VisibilityHighKMs', 'VisibilityLowKMs', 'WindKMPH', 'PrecipitationSumMM'

##### 2.1  Chuyển đổi cột nhiệt độ cao nhất từ độ F sang độ C và lưu vào cột TempHighC trong dfWeather2 (làm tròn 2 số lẻ), hiển thị 5 giá trị đầu của TempHighC
    - công thức chuyển từ độ F sang C: C = (F − 32) × 5/9
    - ví dụ chuyển từ 80F sang C: C = (80 - 32) x 5/9 = 26.67C

In [6]:
dfWeather2 = pd.DataFrame({'TempHighC':round((dfWeather['TempHighF']-32)*5/9, 2)})

In [7]:
dfWeather2.head()

   TempHighC
0      36.67
1      37.78
2      37.22
3      38.33
4      37.22

#### 2.2 Chuyển đổi cột nhiệt độ thấp nhất từ độ F sang độ C và lưu vào cột TempLowC trong dfWeather2

In [8]:
dfWeather2['TempLowC'] = round((dfWeather['TempLowF']-32)*5/9, 2)
dfWeather2.head()

   TempHighC  TempLowC
0      36.67     26.11
1      37.78     25.56
2      37.22     24.44
3      38.33     25.56
4      37.22     25.56

##### 2.3 Tính nhiệt độ trung bình TempMediumC trong dfWeather2

In [9]:
dfWeather2['TempMediumC'] = round((dfWeather2['TempHighC']+dfWeather2['TempLowC'])/2, 2)
dfWeather2.head()

   TempHighC  TempLowC  TempMediumC
0      36.67     26.11        31.39
1      37.78     25.56        31.67
2      37.22     24.44        30.83
3      38.33     25.56        31.94
4      37.22     25.56        31.39

##### 2.4 Tạo mới các cột độ ẩm HumidityHighPercent và HumidityLowPercent trong dfWeather2 bằng các cột HumidityHighPercent và HumidityLowPercent trong dfWeather

In [10]:
dfWeather2['HumidityHighPercent'] = dfWeather['HumidityHighPercent']
dfWeather2['HumidityLowPercent'] = dfWeather['HumidityLowPercent']
dfWeather2.head()

   TempHighC  TempLowC  TempMediumC  HumidityHighPercent  HumidityLowPercent
0      36.67     26.11        31.39                   85                  38
1      37.78     25.56        31.67                   91                  35
2      37.22     24.44        30.83                   88                  35
3      38.33     25.56        31.94                   85                  35
4      37.22     25.56        31.39                   85                  31

##### 2.5 Chuyển đổi cột tầm nhìn xa từ miles sang kilomet và lưu vào cột VisibilityHighKMs trong dfWeather2
    - công thức chuyển từ Mile sang Kilomet: km = mile * 1.609344
    - ví dụ chuyển từ 10 mile sang km: km = 10 * 1.609344 = 16.09344 km

In [11]:
dfWeather2['VisibilityHighKMs'] = round(dfWeather['VisibilityHighMiles']*1.609344, 2)
dfWeather2.head()

,TempHighC,TempLowC,TempMediumC,HumidityHighPercent,HumidityLowPercent,VisibilityHighKMs
0,36.67,26.11,31.39,85,38,16.09
1,37.78,25.56,31.67,91,35,16.09
2,37.22,24.44,30.83,88,35,16.09
3,38.33,25.56,31.94,85,35,16.09
4,37.22,25.56,31.39,85,31,16.09

##### 2.6 Chuyển đổi cột tầm nhìn gần từ miles sang kilomet và lưu vào cột VisibilityLowKMs trong dfWeather2

In [12]:
dfWeather2['VisibilityLowKMs'] = round(dfWeather['VisibilityLowMiles']*1.609344, 2)
dfWeather2.head()

,TempHighC,TempLowC,TempMediumC,HumidityHighPercent,HumidityLowPercent,VisibilityHighKMs,VisibilityLowKMs
0,36.67,26.11,31.39,85,38,16.09,9.66
1,37.78,25.56,31.67,91,35,16.09,12.87
2,37.22,24.44,30.83,88,35,16.09,16.09
3,38.33,25.56,31.94,85,35,16.09,16.09
4,37.22,25.56,31.39,85,31,16.09,16.09

##### 2.7 Chuyển đổi cột sức gió từ miles/hour (WindMPH) sang kilomets/hour và lưu vào cột WindKMPH trong dfWeather2

In [13]:
dfWeather2['WindKMPH'] = round(dfWeather['WindMPH']*1.609344, 2)
dfWeather2.head()

,TempHighC,TempLowC,TempMediumC,HumidityHighPercent,HumidityLowPercent,VisibilityHighKMs,VisibilityLowKMs,WindKMPH
0,36.67,26.11,31.39,85,38,16.09,9.66,24.14
1,37.78,25.56,31.67,91,35,16.09,12.87,22.53
2,37.22,24.44,30.83,88,35,16.09,16.09,20.92
3,38.33,25.56,31.94,85,35,16.09,16.09,20.92
4,37.22,25.56,31.39,85,31,16.09,16.09,20.92

##### 2.8 Chuyển đổi cột lượng mưa từ inches sang milimet và lưu vào cột PrecipitationSumMMs trong dfWeather2
    - công thức chuyển từ Inches sang Milimet: mm = inches * 25.4
    - ví dụ chuyển từ 10 inches sang milimet: mm = 10 * 25.4 = 254 mm

In [14]:
dfWeather2['PrecipitationSumMMs'] = round(dfWeather['PrecipitationSumInches']*25.4, 2)
dfWeather2.head()

,TempHighC,TempLowC,TempMediumC,HumidityHighPercent,HumidityLowPercent,VisibilityHighKMs,VisibilityLowKMs,WindKMPH,PrecipitationSumMMs
0,36.67,26.11,31.39,85,38,16.09,9.66,24.14,0.25
1,37.78,25.56,31.67,91,35,16.09,12.87,22.53,0.00
2,37.22,24.44,30.83,88,35,16.09,16.09,20.92,0.00
3,38.33,25.56,31.94,85,35,16.09,16.09,20.92,0.00
4,37.22,25.56,31.39,85,31,16.09,16.09,20.92,0.00

In [15]:
dfWeather2.shape

(31, 9)

### 3. Xem thông tin thời tiết của 5 ngày đầu tiên trong dfWeather2

In [16]:
dfWeather2.head()

,TempHighC,TempLowC,TempMediumC,HumidityHighPercent,HumidityLowPercent,VisibilityHighKMs,VisibilityLowKMs,WindKMPH,PrecipitationSumMMs
0,36.67,26.11,31.39,85,38,16.09,9.66,24.14,0.25
1,37.78,25.56,31.67,91,35,16.09,12.87,22.53,0.00
2,37.22,24.44,30.83,88,35,16.09,16.09,20.92,0.00
3,38.33,25.56,31.94,85,35,16.09,16.09,20.92,0.00
4,37.22,25.56,31.39,85,31,16.09,16.09,20.92,0.00

### 4. Từ dfWeather2, liệt kê thông tin thời tiết của các ngày có nhiệt độ trung bình cao nhất

In [17]:
maxTemp = dfWeather2['TempMediumC'].max()
dfWeather2[dfWeather2['TempMediumC']==maxTemp]

,TempHighC,TempLowC,TempMediumC,HumidityHighPercent,HumidityLowPercent,VisibilityHighKMs,VisibilityLowKMs,WindKMPH,PrecipitationSumMMs
29,41.11,26.11,33.61,69,27,16.09,16.09,20.92,0.0

### 5. Từ dfWeather2, liệt kê thông tin thời tiết của các ngày có nhiệt độ trung bình thấp nhất

In [18]:
minTemp = dfWeather2['TempMediumC'].min()
dfWeather2[dfWeather2['TempMediumC']==minTemp]

,TempHighC,TempLowC,TempMediumC,HumidityHighPercent,HumidityLowPercent,VisibilityHighKMs,VisibilityLowKMs,WindKMPH,PrecipitationSumMMs
15,37.22,20.0,28.61,100,33,16.09,9.66,19.31,0.0

### 6. Từ dfWeather2, liệt kê thông tin thời tiết của các ngày có mưa, sắp giảm theo lượng mưa

In [19]:
dfWeather2[dfWeather2['PrecipitationSumMMs']>0].sort_values(by='PrecipitationSumMMs', ascending=False)

,TempHighC,TempLowC,TempMediumC,HumidityHighPercent,HumidityLowPercent,VisibilityHighKMs,VisibilityLowKMs,WindKMPH,PrecipitationSumMMs
14,39.44,21.67,30.56,100,29,16.09,3.22,37.01,4.06
22,39.44,25.00,32.22,85,31,16.09,3.22,20.92,1.02
16,36.67,25.00,30.84,88,38,16.09,16.09,25.75,0.76
6,37.22,23.89,30.56,88,33,16.09,16.09,24.14,0.51
0,36.67,26.11,31.39,85,38,16.09,9.66,24.14,0.25
20,40.00,25.00,32.50,85,27,16.09,16.09,22.53,0.25
23,38.89,24.44,31.66,91,29,16.09,14.48,20.92,0.25
25,39.44,25.56,32.50,91,25,16.09,16.09,24.14,0.25

### 7. Từ dfWeather2, liệt kê thông tin thời tiết của các ngày không có mưa và có độ ẩm trung bình cao nhất

In [20]:
maxHumidityMedium = ((dfWeather2['HumidityHighPercent']+dfWeather2['HumidityLowPercent'])/2).max()
print('độ ẩm trung bình cao nhất:', maxHumidityMedium)
cond = (dfWeather2['PrecipitationSumMMs']==0) & ((dfWeather2['HumidityHighPercent']+dfWeather2['HumidityLowPercent'])/2==maxHumidityMedium)
dfWeather2[cond]

độ ẩm trung bình cao nhất: 66.5

,TempHighC,TempLowC,TempMediumC,HumidityHighPercent,HumidityLowPercent,VisibilityHighKMs,VisibilityLowKMs,WindKMPH,PrecipitationSumMMs
15,37.22,20.0,28.61,100,33,16.09,9.66,19.31,0.0

### 8. Tạo series temp_medium chứa hai giá trị trung bình cột TempMediumC của các ngày có mưa và các ngày không mưa trong tháng

In [21]:
mean_co_mua = dfWeather2[dfWeather2['PrecipitationSumMMs']>0]['TempMediumC'].mean()
mean_khong_mua = dfWeather2[dfWeather2['PrecipitationSumMMs']==0]['TempMediumC'].mean()
temp_medium = pd.Series([mean_co_mua, mean_khong_mua], index=['có mưa','không mưa'])
temp_medium

có mưa       31.528750
không mưa    31.664783
dtype: float64